spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/opticadb
    username: rolek
    password: 123
    driver-class-name:
  jpa:
    show-sql: true
server:
  port: 8082
logging:
  level:
    sql: info